# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simulator.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame = QtWidgets.QFrame(self.frame_8)
        self.frame.setGeometry(QtCore.QRect(10, 10, 762, 241))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(2, 40, 62, 16))
        self.label_2.setObjectName("label_2")
        self.PB_Start = QtWidgets.QPushButton(self.frame)
        self.PB_Start.setGeometry(QtCore.QRect(670, 10, 75, 23))
        self.PB_Start.setObjectName("PB_Start")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(2, 100, 88, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(2, 150, 88, 16))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(2, 0, 98, 16))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(114, 60, 651, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 28, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(116, 20, 28, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(222, 20, 28, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(329, 20, 28, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(435, 20, 28, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(541, 20, 28, 16))
        self.label_10.setObjectName("label_10")
        self.IFUC_1_S1 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_S1.setGeometry(QtCore.QRect(10, 38, 100, 20))
        self.IFUC_1_S1.setObjectName("IFUC_1_S1")
        self.IFUC_1_S2 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_S2.setGeometry(QtCore.QRect(116, 38, 100, 20))
        self.IFUC_1_S2.setObjectName("IFUC_1_S2")
        self.IFUC_1_S3 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_S3.setGeometry(QtCore.QRect(222, 38, 101, 20))
        self.IFUC_1_S3.setObjectName("IFUC_1_S3")
        self.IFUC_1_S4 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_S4.setGeometry(QtCore.QRect(329, 38, 100, 20))
        self.IFUC_1_S4.setObjectName("IFUC_1_S4")
        self.IFUC_1_S5 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_S5.setGeometry(QtCore.QRect(435, 38, 100, 20))
        self.IFUC_1_S5.setObjectName("IFUC_1_S5")
        self.IFUC_1_S6 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_S6.setGeometry(QtCore.QRect(541, 38, 100, 20))
        self.IFUC_1_S6.setObjectName("IFUC_1_S6")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 28, 16))
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(116, 70, 28, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(222, 70, 28, 16))
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(329, 70, 28, 16))
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(435, 70, 28, 16))
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(541, 70, 28, 16))
        self.label_15.setObjectName("label_15")
        self.IFUC_1_L1 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_L1.setGeometry(QtCore.QRect(10, 91, 100, 20))
        self.IFUC_1_L1.setObjectName("IFUC_1_L1")
        self.IFUC_1_L2 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_L2.setGeometry(QtCore.QRect(116, 91, 100, 20))
        self.IFUC_1_L2.setObjectName("IFUC_1_L2")
        self.IFUC_1_L3 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_L3.setGeometry(QtCore.QRect(222, 91, 101, 20))
        self.IFUC_1_L3.setObjectName("IFUC_1_L3")
        self.IFUC_1_L4 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_L4.setGeometry(QtCore.QRect(329, 91, 100, 20))
        self.IFUC_1_L4.setObjectName("IFUC_1_L4")
        self.IFUC_1_L5 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_L5.setGeometry(QtCore.QRect(435, 91, 100, 20))
        self.IFUC_1_L5.setObjectName("IFUC_1_L5")
        self.IFUC_1_L6 = QtWidgets.QLineEdit(self.frame_2)
        self.IFUC_1_L6.setGeometry(QtCore.QRect(541, 91, 100, 20))
        self.IFUC_1_L6.setObjectName("IFUC_1_L6")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(-2, 174, 761, 59))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(126, 10, 77, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(337, 10, 82, 16))
        self.label_19.setObjectName("label_19")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(2, 29, 118, 16))
        self.label_17.setObjectName("label_17")
        self.IFUC_1_DoR = QtWidgets.QLineEdit(self.frame_5)
        self.IFUC_1_DoR.setGeometry(QtCore.QRect(126, 29, 181, 20))
        self.IFUC_1_DoR.setObjectName("IFUC_1_DoR")
        self.IFUC_1_Sw = QtWidgets.QLineEdit(self.frame_5)
        self.IFUC_1_Sw.setGeometry(QtCore.QRect(337, 29, 421, 20))
        self.IFUC_1_Sw.setObjectName("IFUC_1_Sw")
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        self.label_20.setGeometry(QtCore.QRect(0, 119, 118, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_5)
        self.label_21.setGeometry(QtCore.QRect(0, 130, 62, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(0, 190, 88, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(0, 240, 88, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setGeometry(QtCore.QRect(0, 90, 98, 16))
        self.label_24.setObjectName("label_24")
        self.IFUC_1_HLT = QtWidgets.QLineEdit(self.frame)
        self.IFUC_1_HLT.setGeometry(QtCore.QRect(125, 0, 211, 20))
        self.IFUC_1_HLT.setObjectName("IFUC_1_HLT")
        self.IFUC_1_MD = QtWidgets.QLineEdit(self.frame)
        self.IFUC_1_MD.setGeometry(QtCore.QRect(125, 39, 211, 20))
        self.IFUC_1_MD.setObjectName("IFUC_1_MD")
        self.frame_3 = QtWidgets.QFrame(self.frame_8)
        self.frame_3.setGeometry(QtCore.QRect(7, 283, 762, 241))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(2, 40, 62, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(2, 100, 88, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(2, 150, 88, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(2, 0, 111, 16))
        self.label_28.setObjectName("label_28")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(114, 60, 651, 121))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 28, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        self.label_30.setGeometry(QtCore.QRect(116, 20, 28, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(222, 20, 28, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_4)
        self.label_32.setGeometry(QtCore.QRect(329, 20, 28, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame_4)
        self.label_33.setGeometry(QtCore.QRect(435, 20, 28, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_4)
        self.label_34.setGeometry(QtCore.QRect(541, 20, 28, 16))
        self.label_34.setObjectName("label_34")
        self.IFUC_2_S1 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_S1.setGeometry(QtCore.QRect(10, 38, 100, 20))
        self.IFUC_2_S1.setObjectName("IFUC_2_S1")
        self.IFUC_2_S2 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_S2.setGeometry(QtCore.QRect(116, 38, 100, 20))
        self.IFUC_2_S2.setObjectName("IFUC_2_S2")
        self.IFUC_2_S3 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_S3.setGeometry(QtCore.QRect(222, 38, 101, 20))
        self.IFUC_2_S3.setObjectName("IFUC_2_S3")
        self.IFUC_2_S4 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_S4.setGeometry(QtCore.QRect(329, 38, 100, 20))
        self.IFUC_2_S4.setObjectName("IFUC_2_S4")
        self.IFUC_2_S5 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_S5.setGeometry(QtCore.QRect(435, 38, 100, 20))
        self.IFUC_2_S5.setObjectName("IFUC_2_S5")
        self.IFUC_2_S6 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_S6.setGeometry(QtCore.QRect(541, 38, 100, 20))
        self.IFUC_2_S6.setObjectName("IFUC_2_S6")
        self.label_35 = QtWidgets.QLabel(self.frame_4)
        self.label_35.setGeometry(QtCore.QRect(10, 70, 28, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame_4)
        self.label_36.setGeometry(QtCore.QRect(116, 70, 28, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame_4)
        self.label_37.setGeometry(QtCore.QRect(222, 70, 28, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_4)
        self.label_38.setGeometry(QtCore.QRect(329, 70, 28, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.frame_4)
        self.label_39.setGeometry(QtCore.QRect(435, 70, 28, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_4)
        self.label_40.setGeometry(QtCore.QRect(541, 70, 28, 16))
        self.label_40.setObjectName("label_40")
        self.IFUC_2_L1 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_L1.setGeometry(QtCore.QRect(10, 91, 100, 20))
        self.IFUC_2_L1.setObjectName("IFUC_2_L1")
        self.IFUC_2_L2 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_L2.setGeometry(QtCore.QRect(116, 91, 100, 20))
        self.IFUC_2_L2.setObjectName("IFUC_2_L2")
        self.IFUC_2_L3 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_L3.setGeometry(QtCore.QRect(222, 91, 101, 20))
        self.IFUC_2_L3.setObjectName("IFUC_2_L3")
        self.IFUC_2_L4 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_L4.setGeometry(QtCore.QRect(329, 91, 100, 20))
        self.IFUC_2_L4.setObjectName("IFUC_2_L4")
        self.IFUC_2_L5 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_L5.setGeometry(QtCore.QRect(435, 91, 100, 20))
        self.IFUC_2_L5.setObjectName("IFUC_2_L5")
        self.IFUC_2_L6 = QtWidgets.QLineEdit(self.frame_4)
        self.IFUC_2_L6.setGeometry(QtCore.QRect(541, 91, 100, 20))
        self.IFUC_2_L6.setObjectName("IFUC_2_L6")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(-2, 174, 761, 59))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_41 = QtWidgets.QLabel(self.frame_6)
        self.label_41.setGeometry(QtCore.QRect(126, 10, 77, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_6)
        self.label_42.setGeometry(QtCore.QRect(337, 10, 82, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_6)
        self.label_43.setGeometry(QtCore.QRect(2, 29, 118, 16))
        self.label_43.setObjectName("label_43")
        self.IFUC_2_DoR = QtWidgets.QLineEdit(self.frame_6)
        self.IFUC_2_DoR.setGeometry(QtCore.QRect(126, 29, 181, 20))
        self.IFUC_2_DoR.setObjectName("IFUC_2_DoR")
        self.IFUC_2_Sw = QtWidgets.QLineEdit(self.frame_6)
        self.IFUC_2_Sw.setGeometry(QtCore.QRect(337, 29, 421, 20))
        self.IFUC_2_Sw.setObjectName("IFUC_2_Sw")
        self.label_44 = QtWidgets.QLabel(self.frame_6)
        self.label_44.setGeometry(QtCore.QRect(0, 119, 118, 16))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.frame_6)
        self.label_45.setGeometry(QtCore.QRect(0, 130, 62, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_6)
        self.label_46.setGeometry(QtCore.QRect(0, 190, 88, 16))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.frame_6)
        self.label_47.setGeometry(QtCore.QRect(0, 240, 88, 16))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.frame_6)
        self.label_48.setGeometry(QtCore.QRect(0, 90, 98, 16))
        self.label_48.setObjectName("label_48")
        self.IFUC_2_HLT = QtWidgets.QLineEdit(self.frame_3)
        self.IFUC_2_HLT.setGeometry(QtCore.QRect(125, 0, 211, 20))
        self.IFUC_2_HLT.setObjectName("IFUC_2_HLT")
        self.IFUC_1_MD_2 = QtWidgets.QLineEdit(self.frame_3)
        self.IFUC_1_MD_2.setGeometry(QtCore.QRect(125, 39, 211, 20))
        self.IFUC_1_MD_2.setObjectName("IFUC_1_MD_2")
        self.gridLayout_2.addWidget(self.frame_8, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "IFUC 1 Mode"))
        self.PB_Start.setText(_translate("MainWindow", "Start"))
        self.label_3.setText(_translate("MainWindow", "IFUC 1 Slot Status"))
        self.label_4.setText(_translate("MainWindow", "IFUC 1 Link Status"))
        self.label.setText(_translate("MainWindow", "IFUC1 Health Status"))
        self.label_5.setText(_translate("MainWindow", "Slot-1"))
        self.label_6.setText(_translate("MainWindow", "Slot-2"))
        self.label_7.setText(_translate("MainWindow", "Slot-3"))
        self.label_8.setText(_translate("MainWindow", "Slot-4"))
        self.label_9.setText(_translate("MainWindow", "Slot-5"))
        self.label_10.setText(_translate("MainWindow", "Slot-6"))
        self.label_14.setText(_translate("MainWindow", "Link-1"))
        self.label_12.setText(_translate("MainWindow", "Link-2"))
        self.label_13.setText(_translate("MainWindow", "Link-3"))
        self.label_11.setText(_translate("MainWindow", "Link-4"))
        self.label_16.setText(_translate("MainWindow", "Link-5"))
        self.label_15.setText(_translate("MainWindow", "Link-6"))
        self.label_18.setText(_translate("MainWindow", "Date of Release"))
        self.label_19.setText(_translate("MainWindow", "Software Version"))
        self.label_17.setText(_translate("MainWindow", "IFUC 1 Software Version"))
        self.label_20.setText(_translate("MainWindow", "IFUC 1 Software Version"))
        self.label_21.setText(_translate("MainWindow", "IFUC 1 Mode"))
        self.label_22.setText(_translate("MainWindow", "IFUC 1 Slot Status"))
        self.label_23.setText(_translate("MainWindow", "IFUC 1 Link Status"))
        self.label_24.setText(_translate("MainWindow", "IFUC1 Health Status"))
        self.label_25.setText(_translate("MainWindow", "IFUC 2 Mode"))
        self.label_26.setText(_translate("MainWindow", "IFUC 2 Slot Status"))
        self.label_27.setText(_translate("MainWindow", "IFUC 2 Link Status"))
        self.label_28.setText(_translate("MainWindow", "IFUC 2 Health Status"))
        self.label_29.setText(_translate("MainWindow", "Slot-1"))
        self.label_30.setText(_translate("MainWindow", "Slot-2"))
        self.label_31.setText(_translate("MainWindow", "Slot-3"))
        self.label_32.setText(_translate("MainWindow", "Slot-4"))
        self.label_33.setText(_translate("MainWindow", "Slot-5"))
        self.label_34.setText(_translate("MainWindow", "Slot-6"))
        self.label_35.setText(_translate("MainWindow", "Link-1"))
        self.label_36.setText(_translate("MainWindow", "Link-2"))
        self.label_37.setText(_translate("MainWindow", "Link-3"))
        self.label_38.setText(_translate("MainWindow", "Link-4"))
        self.label_39.setText(_translate("MainWindow", "Link-5"))
        self.label_40.setText(_translate("MainWindow", "Link-6"))
        self.label_41.setText(_translate("MainWindow", "Date of Release"))
        self.label_42.setText(_translate("MainWindow", "Software Version"))
        self.label_43.setText(_translate("MainWindow", "IFUC 2 Software Version"))
        self.label_44.setText(_translate("MainWindow", "IFUC 1 Software Version"))
        self.label_45.setText(_translate("MainWindow", "IFUC 1 Mode"))
        self.label_46.setText(_translate("MainWindow", "IFUC 1 Slot Status"))
        self.label_47.setText(_translate("MainWindow", "IFUC 1 Link Status"))
        self.label_48.setText(_translate("MainWindow", "IFUC1 Health Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
